AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  certificateArn:
    Type: String
    
Resources:
  AWSDeepRacerThing:
    Type: AWS::IoT::Thing

  AWSDeepRacerThingPrincipalAttachment:
    Type: AWS::IoT::ThingPrincipalAttachment
    Properties:
      ThingName: !Ref AWSDeepRacerThing
      Principal: !Ref certificateArn

  AWSDeepRacerPolicyPrincipalAttachment:
    Type: AWS::IoT::PolicyPrincipalAttachment
    Properties:
      PolicyName: !Ref AWSDeepRacerPolicy
      Principal: !Ref certificateArn

  AWSDeepRacerPolicy:  
    Type: AWS::IoT::Policy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - iot:Connect
          - iot:Publish
          - iot:Receive
          - iot:Subscribe
          Resource:
          - "*"
      PolicyName: PolicyName
Outputs:
  AWSDeepRacerThing:
    Value: !Ref AWSDeepRacerThing